export const ADD_NEW_EXPENDITURE = "ADD_NEW_EXPENDITURE";
export const RENDER_SPENDING_LIST = "RENDER_SPENDING_LIST";
export const ADD_SPENDING_LIST_ITEM = "ADD_SPENDING_LIST_ITEM";
export const COLOR_NEW_EXPENDITURE_ITEM = "COLOR_NEW_EXPENDITURE_ITEM";
export const CREATE_STATISTICS_LIST = "CREATE_STATISTICS_LIST";
export const SHOW_FILTERED_STATISTICS = "SHOW_FILTERED_STATISTICS";
export const REPLENISH_THE_BALANCE = "REPLENISH_THE_BALANCE";
